### ISSUE TITLE
install and run mock issue

### ISSUE THREAD

**Issue by NHT99** [sunnut/react-easy-start#2]
i try to install by npm install but it's notify me that 
" added 2016 packages from 974 contributors and audited 2083 packages in 132.66s
found 2891 vulnerabilities (1823 low, 26 moderate, 1040 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details "
  Then i try to run 'npm run mock ' and access to localhost:8889 but it's notify me that no resource.
How can i fix that ? :((

**Comment by sunnut** [comment]
please check the nodejs version. It's ok for nodejs 8.x

**Comment by sunnut** [comment]
> i try to install by npm install but it's notify me that
> " added 2016 packages from 974 contributors and audited 2083 packages in 132.66s
> found 2891 vulnerabilities (1823 low, 26 moderate, 1040 high, 2 critical)
> run `npm audit fix` to fix them, or `npm audit` for details "
> Then i try to run 'npm run mock ' and access to localhost:8889 but it's notify me that no resource.
> How can i fix that ? :((

please check the nodejs version. It's ok for nodejs 8.x
